package com.lfy.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE.
 */
public class Message {

    private String conv_id;
    private String message_id;
    private String message_text;

    public Message() {
    }

    public Message(String conv_id) {
        this.conv_id = conv_id;
    }

    public Message(String conv_id, String message_id, String message_text) {
        this.conv_id = conv_id;
        this.message_id = message_id;
        this.message_text = message_text;
    }

    public String getConv_id() {
        return conv_id;
    }

    public void setConv_id(String conv_id) {
        this.conv_id = conv_id;
    }

    public String getMessage_id() {
        return message_id;
    }

    public void setMessage_id(String message_id) {
        this.message_id = message_id;
    }

    public String getMessage_text() {
        return message_text;
    }

    public void setMessage_text(String message_text) {
        this.message_text = message_text;
    }

}
