package com.lfy.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE.
 */
public class Message {

    private String houseId;
    private String leanId;
    private String message;
    private String date;
    private String is_read;
    private String auditType;

    public Message() {
    }

    public Message(String houseId) {
        this.houseId = houseId;
    }

    public Message(String houseId, String leanId, String message, String date, String is_read, String auditType) {
        this.houseId = houseId;
        this.leanId = leanId;
        this.message = message;
        this.date = date;
        this.is_read = is_read;
        this.auditType = auditType;
    }

    public String getHouseId() {
        return houseId;
    }

    public void setHouseId(String houseId) {
        this.houseId = houseId;
    }

    public String getLeanId() {
        return leanId;
    }

    public void setLeanId(String leanId) {
        this.leanId = leanId;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getIs_read() {
        return is_read;
    }

    public void setIs_read(String is_read) {
        this.is_read = is_read;
    }

    public String getAuditType() {
        return auditType;
    }

    public void setAuditType(String auditType) {
        this.auditType = auditType;
    }

}
